# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import time  # NEZBYTNÉ PRO VÝPOČET STATISTIK
import geopandas as gpd
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import *
from PyQt6.QtGui import *

from algorithms import *
from draw import Draw


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        # Standard PyQt6 UI initialization generated by Qt Designer
        MainForm.setObjectName("MainForm")
        MainForm.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(parent=MainForm)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        # Inject our custom drawing canvas widget into the main layout
        self.Canvas = Draw(parent=self.centralwidget)
        self.Canvas.setObjectName("Canvas")
        self.horizontalLayout.addWidget(self.Canvas)
        MainForm.setCentralWidget(self.centralwidget)
        
        # Menubar setup
        self.menubar = QtWidgets.QMenuBar(parent=MainForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSimplify = QtWidgets.QMenu(parent=self.menubar)
        self.menuSimplify.setObjectName("menuSimplify")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        MainForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainForm)
        self.statusbar.setObjectName("statusbar")
        MainForm.setStatusBar(self.statusbar)
        
        # Toolbar and Action setups (Icons, Tooltips)
        self.toolBar = QtWidgets.QToolBar(parent=MainForm)
        self.toolBar.setObjectName("toolBar")
        MainForm.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        
        self.actionExit = QtGui.QAction(parent=MainForm)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        
        self.actionMin_Bounding_Rectangle = QtGui.QAction(parent=MainForm)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/maer.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionMin_Bounding_Rectangle.setIcon(icon1)
        self.actionMin_Bounding_Rectangle.setObjectName("actionMin_Bounding_Rectangle")
        
        self.actionPCAS = QtGui.QAction(parent=MainForm)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/pca.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionPCAS.setIcon(icon2)
        self.actionPCAS.setObjectName("actionPCAS")
        
        self.actionClear_results = QtGui.QAction(parent=MainForm)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/clear_ch.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_results.setIcon(icon3)
        self.actionClear_results.setObjectName("actionClear_results")
        
        self.actionClear_all = QtGui.QAction(parent=MainForm)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/clear_er.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_all.setIcon(icon4)
        self.actionClear_all.setObjectName("actionClear_all")
        
        self.actionLongest_Edge = QtGui.QAction(parent=MainForm)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/longestedge.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionLongest_Edge.setIcon(icon5)
        self.actionLongest_Edge.setObjectName("actionLongest_Edge")
        
        self.actionWall_Average = QtGui.QAction(parent=MainForm)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/wa.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionWall_Average.setIcon(icon6)
        self.actionWall_Average.setObjectName("actionWall_Average")
        
        self.actionWeighted_bisector = QtGui.QAction(parent=MainForm)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/weightedbisector.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionWeighted_bisector.setIcon(icon7)
        self.actionWeighted_bisector.setObjectName("actionWeighted_bisector")
        
        self.actionOpen = QtGui.QAction(parent=MainForm)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/open_file.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen.setIcon(icon8)
        self.actionOpen.setObjectName("actionOpen")
        
        # Linking actions to graphical menus and toolbar
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSimplify.addAction(self.actionMin_Bounding_Rectangle)
        self.menuSimplify.addAction(self.actionPCAS)
        self.menuSimplify.addAction(self.actionLongest_Edge)
        self.menuSimplify.addAction(self.actionWall_Average)
        self.menuSimplify.addAction(self.actionWeighted_bisector)
        self.menuView.addAction(self.actionClear_results)
        self.menuView.addAction(self.actionClear_all)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSimplify.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMin_Bounding_Rectangle)
        self.toolBar.addAction(self.actionPCAS)
        self.toolBar.addAction(self.actionLongest_Edge)
        self.toolBar.addAction(self.actionWall_Average)
        self.toolBar.addAction(self.actionWeighted_bisector)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear_results)
        self.toolBar.addAction(self.actionClear_all)
        self.toolBar.addSeparator()
        
        # =========================================================
        # SIGNALS AND SLOTS BINDING (Tohle zapínalo tlačítka!)
        # =========================================================
        self.actionMin_Bounding_Rectangle.triggered.connect(self.simplifyBuildingMBRClick)
        self.actionPCAS.triggered.connect(self.simplifyBuildingPCAClick)
        self.actionLongest_Edge.triggered.connect(self.simplifyBuildingLongestEdgeClick)
        self.actionWall_Average.triggered.connect(self.simplifyBuildingWallAverageClick)
        self.actionWeighted_bisector.triggered.connect(self.simplifyBuildingWeightedBisectorClick)
        self.actionClear_results.triggered.connect(self.clearResultsClick)
        self.actionClear_all.triggered.connect(self.clearAllClick)
        self.actionOpen.triggered.connect(self.openShapefileClick)
        self.actionExit.triggered.connect(MainForm.close) # Aby fungovalo i tlačítko Exit

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)


    # =========================================================
    # GENERALIZATION & STATISTICS ENGINE
    # =========================================================

    def runAlgorithm(self, algorithm_function, algorithm_name):
        """Master function to run any algorithm, measure time, and calculate statistics."""
        buildings = self.Canvas.getBuildings()
        if not buildings:
            QtWidgets.QMessageBox.warning(self.centralwidget, "Pozor", "Nejprve načtěte data (*.shp).")
            return
            
        a = Algorithms()
        mbrs_res = []
        
        # Statistics variables
        valid_count = 0
        orig_perim_total = 0.0
        gen_perim_total = 0.0
        
        # Start highly precise timer
        start_time = time.perf_counter()
        
        for building in buildings:
            if len(building) >= 3:
                try:
                    # Execute the passed algorithm function dynamically
                    res = algorithm_function(a, building)
                    mbrs_res.append(res)
                    
                    # Accumulate perimeter stats
                    orig_perim_total += a.getPerimeter(building)
                    gen_perim_total += a.getPerimeter(res)
                    valid_count += 1
                    
                except Exception as e:
                    print(f"Skipping geometry in {algorithm_name}: {e}")
                    
        # Stop timer
        end_time = time.perf_counter()
        total_time = end_time - start_time
        
        # Render results
        self.Canvas.setMBRs(mbrs_res)
        
        # Display statistics to the user
        if valid_count > 0:
            avg_orig_p = orig_perim_total / valid_count
            avg_gen_p = gen_perim_total / valid_count
            reduction = (1 - (avg_gen_p / avg_orig_p)) * 100 if avg_orig_p > 0 else 0
            
            msg = f"<b>Metoda:</b> {algorithm_name}<br><br>"
            msg += f"<b>Zpracováno budov:</b> {valid_count}<br>"
            msg += f"<b>Celkový čas výpočtu:</b> {total_time:.4f} s<br><br>"
            msg += f"<b>Průměrný obvod (Původní):</b> {avg_orig_p:.2f} jednotek<br>"
            msg += f"<b>Průměrný obvod (LOD0):</b> {avg_gen_p:.2f} jednotek<br>"
            msg += f"<b>Vyhlazení (zmenšení obvodu):</b> {reduction:.1f} %"
            
            QtWidgets.QMessageBox.information(self.centralwidget, "Statistika generalizace", msg)


    # =========================================================
    # BUTTON CLICK HANDLERS
    # =========================================================

    def simplifyBuildingMBRClick(self):
        self.runAlgorithm(Algorithms.simplifyBuildingMBR, "Minimum Bounding Rectangle (MAER)")
        
    def simplifyBuildingPCAClick(self):
        self.runAlgorithm(Algorithms.simplifyBuildingPCA, "Principal Component Analysis (PCA)")
        
    def simplifyBuildingLongestEdgeClick(self):
        self.runAlgorithm(Algorithms.simplifyBuildingLongestEdge, "Longest Edge")
        
    def simplifyBuildingWallAverageClick(self):
        self.runAlgorithm(Algorithms.simplifyBuildingWallAverage, "Wall Average")
        
    def simplifyBuildingWeightedBisectorClick(self):
        self.runAlgorithm(Algorithms.simplifyBuildingWeightedBisector, "Weighted Bisector")


    # =========================================================
    # CUSTOM METHODS AND LOGIC
    # =========================================================

    def loadShapefile(self, path):
        """Loads vector geospatial data using GeoPandas and converts it to QPolygons."""
        try:
            gdf = gpd.read_file(path)
            buildings_list = []
            
            for geom in gdf.geometry:
                if geom.geom_type == 'Polygon':
                    qpoly = QPolygonF()
                    for x, y in geom.exterior.coords:
                        qpoly.append(QPointF(x, y))
                    buildings_list.append(qpoly)
                    
                elif geom.geom_type == 'MultiPolygon':
                    for part in geom.geoms:
                        qpoly = QPolygonF()
                        for x, y in part.exterior.coords:
                            qpoly.append(QPointF(x, y))
                        buildings_list.append(qpoly)
            
            self.Canvas.setBuildings(buildings_list)
            
        except Exception as e:
            QtWidgets.QMessageBox.critical(
                self.centralwidget, "Error", f"Failed to load file:\n{e}"
            )
            
    def openShapefileClick(self):
        """Triggers the OS native file explorer to select a shapefile."""
        path, _ = QtWidgets.QFileDialog.getOpenFileName(
            self.centralwidget, "Open Shapefile", "", "ESRI Shapefiles (*.shp);;All Files (*)"
        )
        if path:
            self.loadShapefile(path)

    def clearAllClick(self):
        """Flushes the primary building list and all processing results from the canvas."""
        self.Canvas.clearAll()
            
    def clearResultsClick(self):
        """Flushes only the generalized rectangles, keeping original raw buildings loaded."""
        self.Canvas.clearResult()
        
    def retranslateUi(self, MainForm):
        # Auto-generated string definitions for the UI components
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Simplify buildings"))
        self.menuFile.setTitle(_translate("MainForm", "File"))
        self.menuSimplify.setTitle(_translate("MainForm", "Simplify"))
        self.menuView.setTitle(_translate("MainForm", "View"))
        self.toolBar.setWindowTitle(_translate("MainForm", "toolBar"))
        self.actionExit.setText(_translate("MainForm", "Exit"))
        self.actionExit.setToolTip(_translate("MainForm", "Close application"))
        self.actionMin_Bounding_Rectangle.setText(_translate("MainForm", "Min. Bounding Rectangle"))
        self.actionMin_Bounding_Rectangle.setToolTip(_translate("MainForm", "Simplify building using minimum bounding rectangle"))
        self.actionPCAS.setText(_translate("MainForm", "PCA"))
        self.actionPCAS.setToolTip(_translate("MainForm", "Simplify building using PCA"))
        self.actionClear_results.setText(_translate("MainForm", "Clear results"))
        self.actionClear_all.setText(_translate("MainForm", "Clear all"))
        self.actionClear_all.setToolTip(_translate("MainForm", "Clear all data"))
        self.actionLongest_Edge.setText(_translate("MainForm", "Longest Edge"))
        self.actionLongest_Edge.setToolTip(_translate("MainForm", "Simplify building using PCA longest edge"))
        self.actionWall_Average.setText(_translate("MainForm", "Wall Average"))
        self.actionWall_Average.setToolTip(_translate("MainForm", "Simplify building using wall average"))
        self.actionWeighted_bisector.setText(_translate("MainForm", "Weighted Bisector"))
        self.actionWeighted_bisector.setToolTip(_translate("MainForm", "Simplify building using weighted bisector"))
        self.actionOpen.setText(_translate("MainForm", "Open"))
        self.actionOpen.setToolTip(_translate("MainForm", "Open file"))


if __name__ == "__main__":
    # Standard application entry point
    app = QtWidgets.QApplication(sys.argv)
    MainForm = QtWidgets.QMainWindow()
    ui = Ui_MainForm()
    ui.setupUi(MainForm)
    MainForm.showMaximized() # MAXIMALIZOVANÉ OKNO
    sys.exit(app.exec())